theme: jekyll-theme-cayman
# The title: appears frequently on my pages. It's your company / personal name
title: Pippim
description: Free Open-Source Software for the World. Free of Ads Too!
# posts_by_year must be true or false. When true subdirectory by year for posts
# Needed for GitHub when more than 1,000 posts in total.
# Used by stack-to-blog.py and theCookieMachine.js
posts_by_year: true
# Link to content on the GitHub Repository. Used by stack-to-blog.py
code_url: https://github.com/pippim/pippim.github.io/blob/main

# Following site-wide values automatically set by sede/refresh.sh script
views: "55,695,177 "
views_human: 55.7 million
refreshed: 2022-05-08 09:37:50
questions: "305 "
answers: "2,169 "
accepted: "476 "
post_count: "1,134 "
question_count: "51 "
answer_count: "1,083 "
accepted_count: "487 "
all_tag_counts: "3,488 "
